name: 'Create release'
outputs:
  tag:
    description: "release tag"
    value: "v${{ steps.create-release.outputs.version }}"

runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v2
  - name: install dependencies
    shell: bash
    run: |
      yarn add @semantic-release/changelog@^6.0.1
      yarn add @semantic-release/error@^2.2.0
      yarn add @semantic-release/git@^10.0.1
      yarn add @semantic-release/release-notes-generator@^10.0.3
      yarn add @semantic-release/github@^8.0.2
      yarn add upgrade@^1.1.0
      yarn add @semantic-release/commit-analyzer@^9.0.2
      yarn add commit-analyzer-fail-on-no-release@^1.0.1

  - name: Release
    shell: bash
    id: create-release
    run: |
      npmx semantic-release
      VERSION=$(cat package.json|jq -r .version)
      echo "::set-output name=version::$VERSION"
    env:
      GITHUB_TOKEN: ${{ github.token }}
