name: 'Create release'
outputs:
  tag:
    description: "release tag"
    value: ${{ steps.create-release.outputs.version }}

runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v2
  - shell: bash
    run: if [[ -f "yarn.lock" ]] ; then yarn install; fi
  - shell: bash
    run: if [[ -f "package-lock.json" ]] ; then npm install ; fi
  - name: Release
    shell: bash
    id: create-release
    run: |
      if [[ -f "yarn.lock" ]] ; then  yarn global add semantic-release && semantic-release ; fi
      if [[ -f "package-lock.json" ]] ; then  npx semantic-release ; fi
      VERSION=$(cat package.json|jq -r .version)
      echo "::set-output name=version::$VERSION"
    env:
      GITHUB_TOKEN: ${{ github.token }}
