name: 'Create release'
outputs:
  tag:
    description: "generate tag by semantic release"
    value: "v${{ steps.create-release.outputs.version }}"
runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v3
    with:
      node-version: 14
  - name: install dependencies
    shell: bash
    run: |
      yarn add semantic-release@19
      yarn add @semantic-release/changelog@^6.0.1
      yarn add @semantic-release/error@^2.2.0
      yarn add @semantic-release/git@^10.0.1
      yarn add @semantic-release/release-notes-generator@^10.0.3
      yarn add upgrade@^1.1.0
      yarn add @semantic-release/commit-analyzer@^9.0.2
      yarn add commit-analyzer-fail-on-no-release@^1.0.1
      yarn add conventional-changelog-conventionalcommits@^4.6.3
  - name: download .releaserc
    shell: bash
    run: |
      if [[ ! -f ".releaserc.json" ]] ; then curl -O https://raw.githubusercontent.com/SharecareBrasil/create-version-action/main/.releaserc.json ; fi
  - name: Release
    shell: bash
    id: create-release
    run: |
      npx semantic-release
      VERSION=$(cat package.json|jq -r .version)
      echo "version=$VERSION" >> $GITHUB_OUTPUT
    env:
      GITHUB_TOKEN: ${{ github.token }}
  - name: Archive changelog
    uses: actions/upload-artifact@v3
    with:
      name: "CHANGELOG"
      path: "CHANGELOG.md"
