name: 'Create release'
outputs:
  tag:
    description: "release tag"
    value: ${{ steps.create-release.outputs.version }}

runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v2
    with:
      cache: npm
  - shell: bash
    run: npm ci
  - name: Release
    shell: bash
    id: create-release
    run: |
      npx semantic-release
      VERSION=$(cat package.json|jq -r .version)
      echo "::set-output name=version::$VERSION"
    env:
      GITHUB_TOKEN: ${{ github.token }}
